In [7]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

Matplotlib is building the font cache; this may take a moment.

In [8]:
PROJECT_ROOT = Path.cwd()

print("Current working directory:")
print(PROJECT_ROOT)

Current working directory:
d:\VS Code\DataPilot\notebooks\phase_01

In [12]:
DATA_PATH = PROJECT_ROOT / "D:\\VS Code\\DataPilot\\data\\raw\\superstore.csv"
print(DATA_PATH)

D:\VS Code\DataPilot\data\raw\superstore.csv

In [13]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()

print("Current working directory:", PROJECT_ROOT)

Current working directory: d:\VS Code\DataPilot\notebooks\phase_01

In [14]:

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [15]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [16]:

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 9800
Columns: 18

In [17]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales']

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [19]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [22]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [23]:
duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 0

In [24]:
# Convert date columns

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    dayfirst=True,
    errors="coerce"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    dayfirst=True,
    errors="coerce"
)

df[["Order Date", "Ship Date"]].head()

  Order Date  Ship Date
0 2017-11-08 2017-11-11
1 2017-11-08 2017-11-11
2 2017-06-12 2017-06-16
3 2016-10-11 2016-10-18
4 2016-10-11 2016-10-18

In [25]:
# Check invalid dates

print("Invalid Order Dates:", df["Order Date"].isnull().sum())
print("Invalid Ship Dates:", df["Ship Date"].isnull().sum())

Invalid Order Dates: 0
Invalid Ship Dates: 0

In [26]:
# Clean Postal Code

df["Postal Code"] = df["Postal Code"].astype("Int64")

df[["Postal Code"]].head()

   Postal Code
0        42420
1        42420
2        90036
3        33311
4        33311

In [29]:
#Create date features
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month
df["Order Month Name"] = df["Order Date"].dt.month_name()
df["Order Quarter"] = df["Order Date"].dt.quarter
df["Order Day"] = df["Order Date"].dt.day


df[
    [
        "Order Date",
        "Order Year",
        "Order Month",
        "Order Month Name",
        "Order Quarter"
    ]
].head()

  Order Date  Order Year  Order Month Order Month Name  Order Quarter
0 2017-11-08        2017           11         November              4
1 2017-11-08        2017           11         November              4
2 2017-06-12        2017            6             June              2
3 2016-10-11        2016           10          October              4
4 2016-10-11        2016           10          October              4

In [30]:
# Cell 21 — Calculate shipping duration

df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

df[
    ["Order Date", "Ship Date", "Shipping Days"]
].head()

  Order Date  Ship Date  Shipping Days
0 2017-11-08 2017-11-11              3
1 2017-11-08 2017-11-11              3
2 2017-06-12 2017-06-16              4
3 2016-10-11 2016-10-18              7
4 2016-10-11 2016-10-18              7

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            9800 non-null   int64
 1   Order ID          9800 non-null   str
 2   Order Date        9800 non-null   datetime64[us]
 3   Ship Date         9800 non-null   datetime64[us]
 4   Ship Mode         9800 non-null   str
 5   Customer ID       9800 non-null   str
 6   Customer Name     9800 non-null   str
 7   Segment           9800 non-null   str
 8   Country           9800 non-null   str
 9   City              9800 non-null   str
 10  State             9800 non-null   str
 11  Postal Code       9789 non-null   Int64
 12  Region            9800 non-null   str
 13  Product ID        9800 non-null   str
 14  Category          9800 non-null   str
 15  Sub-Category      9800 non-null   str
 16  Product Name      9800 non-null   str
 17  Sales             9800 non-null   float64
 18  Order Year        9800 non-null   int32
 19  Order Month       9800 non-null   int32
 20  Order Month Name  9800 non-null   str
 21  Order Quarter     9800 non-null   int32
 22  Order Day         9800 non-null   int32
 23  Shipping Days     9800 non-null   int64
dtypes: Int64(1), datetime64[us](2), float64(1), int32(4), int64(2), str(14)
memory usage: 1.7 MB

In [33]:
duplicate_rows

np.int64(0)

In [34]:
df[["Order Date", "Ship Date", "Shipping Days"]].head()

  Order Date  Ship Date  Shipping Days
0 2017-11-08 2017-11-11              3
1 2017-11-08 2017-11-11              3
2 2017-06-12 2017-06-16              4
3 2016-10-11 2016-10-18              7
4 2016-10-11 2016-10-18              7

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            9800 non-null   int64
 1   Order ID          9800 non-null   str
 2   Order Date        9800 non-null   datetime64[us]
 3   Ship Date         9800 non-null   datetime64[us]
 4   Ship Mode         9800 non-null   str
 5   Customer ID       9800 non-null   str
 6   Customer Name     9800 non-null   str
 7   Segment           9800 non-null   str
 8   Country           9800 non-null   str
 9   City              9800 non-null   str
 10  State             9800 non-null   str
 11  Postal Code       9789 non-null   Int64
 12  Region            9800 non-null   str
 13  Product ID        9800 non-null   str
 14  Category          9800 non-null   str
 15  Sub-Category      9800 non-null   str
 16  Product Name      9800 non-null   str
 17  Sales             9800 non-null   float64
 18  Order Year        9800 non-null   int32
 19  Order Month       9800 non-null   int32
 20  Order Month Name  9800 non-null   str
 21  Order Quarter     9800 non-null   int32
 22  Order Day         9800 non-null   int32
 23  Shipping Days     9800 non-null   int64
dtypes: Int64(1), datetime64[us](2), float64(1), int32(4), int64(2), str(14)
memory usage: 1.7 MB